### ISSUE TITLE
Reconsider base costs in Truck herd and rent pasture

### ISSUE THREAD

**Issue by tshrum** [tshrum/drought_decision_model#42]
Currently, the excel model assumes that the base operating costs per cow are the same regardless of whether the herd is near or far. It seems like sending the herd to rented pasture would reduce the base operating costs?

**Comment by tshrum** [comment]
It does reduce operating costs by $100 per cow.

**Comment by kcarn19** [comment]
As far as I can tell the base operating costs are the same across the board for each option. The reason that I'm trying to find the source for the operating cost, but I think the numbers are correct for base costs. I'm leaving the ticket open, let me know if I missed something
